"use-client";
import type { Metadata } from "next";

import { AppRootLayout } from "@/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: Readonly<Children>) {
  return <AppRootLayout>{children}</AppRootLayout>;
}
