"use-client";
import type { Metadata } from "next";

import { AppBaseLayout } from "@/layouts";
import { LoaderProvider, ThemeProvider } from "@/contexts";

import "@/assets/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Children>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <LoaderProvider>
          <AppBaseLayout>{children}</AppBaseLayout>
        </LoaderProvider>
      </ThemeProvider>
    </html>
  );
}
