"use-client";
import type { Metadata } from "next";

import { Theme } from "@/theme/Theme";
import { LoaderProvider, ThemeProvider } from "@/contexts";

import { Suspense } from "react";
import { Loader } from "@/components/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<Children>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <LoaderProvider>
          <Theme>
            <Suspense fallback={<Loader />}>{children}</Suspense>
          </Theme>
        </LoaderProvider>
      </ThemeProvider>
    </html>
  );
}
