"use-client";
import type { Metadata } from "next";

import { AppAuthLayout } from "@/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: Readonly<Children>) {
  return <AppAuthLayout>{children}</AppAuthLayout>;
}
